export enum AnchorLinkIds {
  ARTICLES = "ARTICLES",
  COMPONENTS = "COMPONENTS",
  PITCH = "PITCH",
  TOKEN = "TOKEN",
  ECOSYSTEM = "ECOSYSTEM",
  DNA = "DNA",
  BLOG = "BLOG",
  WEB3 = "WEB3",
  DECENTRALIZED = "DECENTRALIZED",
  GOVERNANCE = "GOVERNANCE",
}
